#!/usr/local/bin/node

const fs = require("fs")
const readline = require('readline');

const reg = /(docs|feature|chore|fix)\((CCS)\-([0-9]*)\)\: ([a-zA-Z0-9_,. ]+$)|Merge branch/
const fileStream = fs.createReadStream(process.argv[2])
const reader = readline.createInterface({
    input: fileStream,
    crlfDelay: Infinity
})

let valid = false
let commitFirstLine = ""

reader.on("line", function(line) {
    valid = reg.test(line)
    commitFirstLine = line
    fileStream.close()
    reader.close()
})

reader.on("close", function(){
    if (valid) {
        console.log(`\x1b[36mCommit message is valid\x1b[0m`)
        process.exit(0)
    } else {
        const invalidCommitWarning = `[31mProvided commit message is not valid!\n[0m>>>>>>    ${commitFirstLine}    <<<<<<\n[31mPlease provide a valid commit message[0m\n[36mExamples:[0m\n\tfeature(CCS-123): mock message\n\tdocs(CCS-123): mock message\n\tchore(CCS-123): mock message\n\tfix(CCS-123): mock message`
        console.log(invalidCommitWarning)
        process.exit(1)
    }
})
